FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# ===== Build do tpch-dbgen =====
WORKDIR /tpch

RUN git clone https://github.com/electrum/tpch-dbgen.git

WORKDIR /tpch/tpch-dbgen
RUN make

# ===== Código Python =====
WORKDIR /app

COPY app/scripts/generate_tpch/ .
COPY app/scripts/utils/ ./utils
COPY app/scripts/enums/ ./enums

RUN mkdir -p /data/tpch

CMD ["python3", "generate_tpch.py"]