FROM python:3.11-slim

WORKDIR /app

RUN pip install pandas pyarrow duckdb

COPY scripts/pandas_benchmark/ .
COPY scripts/enums/ ./enums
COPY scripts/utils/ ./utils
COPY queries/tpch/ ./queries

CMD ["python", "pandas_benchmark.py"]